# Generated by Django 4.0.4 on 2022-06-16 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('acronym', models.CharField(default='', max_length=3)),
                ('areaID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.area')),
            ],
        ),
        migrations.CreateModel(
            name='PopPlus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('area_OSPF', models.IntegerField()),
                ('octet2_ip_OSPF_MGMT', models.IntegerField()),
                ('octet2_ip_MGMT', models.IntegerField()),
                ('octet3_ip_MGMT', models.IntegerField()),
                ('vlan_PPPoE', models.IntegerField()),
                ('branchID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Pop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ring', models.CharField(max_length=20)),
                ('range_ip', models.GenericIPAddressField()),
                ('vlan_PPPoE', models.CharField(max_length=20)),
                ('metro', models.CharField(max_length=20)),
                ('popPlusID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.popplus')),
                ('provinceID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.province')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=20)),
                ('ip', models.GenericIPAddressField()),
                ('brandID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.brand')),
                ('popID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.pop')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.province'),
        ),
    ]
