# Generated by Django 4.0.4 on 2022-06-17 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='province',
            new_name='provinceID',
        ),
    ]
