# Generated by Django 4.0.4 on 2022-06-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_provinceid_branch_province_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pop',
            name='sequence_ring',
            field=models.IntegerField(default=16),
            preserve_default=False,
        ),
    ]
