# Generated by Django 4.0.4 on 2022-06-19 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pop_sequence_ring'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='popID',
            new_name='pop',
        ),
    ]
