# Generated by Django 4.0.4 on 2022-06-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_device_gateway_device_subnet'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='gateways',
            field=models.GenericIPAddressField(default=None, null=True),
        ),
    ]
