# Generated by Django 4.0.4 on 2022-06-20 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_device_gateways'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='gateways',
        ),
    ]
