# Generated by Django 4.0.5 on 2022-06-20 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_device_gateway_remove_device_subnet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='id',
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='popplus',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.branch'),
        ),
    ]
