# Generated by Django 4.0.4 on 2022-06-22 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_device_gateway_device_subnet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='brand',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='api.brand'),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip',
            field=models.GenericIPAddressField(default=None),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='pop',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='api.pop'),
        ),
        migrations.AlterField(
            model_name='device',
            name='role',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
