# Generated by Django 4.0.4 on 2022-06-22 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_device_brand_alter_device_ip_alter_device_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='company',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(default=None, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='pop',
            name='metro',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='pop',
            name='name',
            field=models.CharField(default=None, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='pop',
            name='popPlus',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='api.popplus'),
        ),
        migrations.AlterField(
            model_name='pop',
            name='province',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='api.province'),
        ),
        migrations.AlterField(
            model_name='pop',
            name='range_ip',
            field=models.GenericIPAddressField(default=None, unique=True),
        ),
        migrations.AlterField(
            model_name='pop',
            name='ring',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='pop',
            name='sequence_ring',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='pop',
            name='vlan_PPPoE',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='popplus',
            name='area_OSPF',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='popplus',
            name='branch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='api.branch'),
        ),
        migrations.AlterField(
            model_name='popplus',
            name='name',
            field=models.CharField(default=None, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='popplus',
            name='octet2_ip_MGMT',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='popplus',
            name='octet2_ip_OSPF_MGMT',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='popplus',
            name='octet3_ip_MGMT',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='popplus',
            name='vlan_PPPoE',
            field=models.IntegerField(default=None),
        ),
    ]
